
pipeline {
    agent any
    stages {
        stage ('Workspace Clean') {
            steps {
             cleanWs()   
            }
        }
        // stage ('Build - npm build') {
        //     steps {
        //         sh script: """\
        //                     echo ${WORKSPACE}
        //                     git clone https://github.com/kimdragon50/facam-frontend.git 
        //                     cd facam-frontend 
        //                     npm install 
        //                     npm build 
        //                     cp -r build/* /usr/share/nginx/html/
        //                     """, returnStdout: true
        //     }
        // }
        stage ('Build - Maven build') {
            steps {
                sh script: """\
                            echo ${WORKSPACE}
                            git clone https://github.com/kimdragon50/facam-backend.git 
                            cd facam-backend
                            mvn clean
                            mvn package 
                            cp -r ./target/*.jar /usr/local/share
                            """, returnStdout: true
            }
        }
        stage ('Deploy') {
            steps {
                sh script: """\
                            git clone https://github.com/kimdragon50/facam-ansible.git 
                            cd  facam-ansible 
                            ansible-playbook deploy_backend.yml -i ./hosts/hosts --extra-vars "deploy_hosts=app" 
                            """, returnStdout: true
            }
        }
    }
}



