
pipeline {
    agent any
    stages {
        // stage ('Build - npm build') {
        //     steps {
        //         sh script: """\
        //                     echo ${WORKSPACE}
        //                     git clone https://github.com/kimdragon50/facam-frontend.git 
        //                     cd facam-frontend 
        //                     npm install 
        //                     npm build 
        //                     cp -r build/* /usr/share/nginx/html/
        //                     """, returnStdout: true
        //     }
        // }
        stage ('git clone') {
            steps {
                sh  """
                    echo ${WORKSPACE}
                    git clone https://github.com/kimdragon50/facam-backend.git 
                    """
            }
        }
        stage ('Maven Build') {
            steps {
                sh  """
                    cd facam-backend
                    mvn clean
                    mvn package 
                    """
            }
        }
        // stage ('copy jar') {
        //     steps {
        //         sh  """
        //             cd facam-backend
        //             pwd
        //             chmod 755 ./target/employee-management-backend-0.0.1-SNAPSHOT.jar
        //             cp ./target/employee-management-backend-0.0.1-SNAPSHOT.jar /usr/local/share
        //             """
        //     }
        // }
        stage ('Ansible Deploy') {
            steps {
                sh  """
                    git clone https://github.com/kimdragon50/facam-ansible.git 
                    cd  facam-ansible 
                    ansible-playbook deploy_backend.yml -i ./hosts/hosts --extra-vars "deploy_hosts=app" 
                    """
            }
        }
        stage ('Workspace Clean') {
            steps {
             cleanWs()   
            }
        }
    }
}



